name: Build sample invoice (manual)

on:
  workflow_dispatch:  # ручной запуск из вкладки Actions

permissions:
  contents: write     # нужно, чтобы закоммитить PNG-превью

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install reportlab

      - name: Build sample invoice (use generator.generate_invoice or placeholder)
        run: |
          python - <<'PY'
          import os, json, sys
          os.makedirs("examples", exist_ok=True)
          inp = "examples/sample_input.json"
          out = "examples/sample_invoice.pdf"

          # создаём пример входа, если его нет
          if not os.path.exists(inp):
            with open(inp, "w", encoding="utf-8") as f:
              json.dump({
                "invoice_no": "INV-0001",
                "date": "2025-09-01",
                "due_date": "2025-09-15",
                "currency": "EUR",
                "seller": {"name": "Demo s.r.o.", "iban": "SK00 0000 0000 0000 0000 0000"},
                "buyer":  {"name": "Sample Client s.r.o."},
                "items":  [{"name": "Service A", "qty": 1, "price": 100.0, "vat_rate": 0.20}],
                "variable_symbol": "20250901"
              }, f, ensure_ascii=False, indent=2)

          ok = False
          # пробуем generator.py в корне
          try:
            from generator import generate_invoice as _gen
            _gen(inp, out)
            ok = True
          except Exception as e1:
            # пробуем src/generator.py
            try:
              sys.path.append("src")
              from generator import generate_invoice as _gen
              _gen(inp, out)
              ok = True
            except Exception as e2:
              print("Generator not found/failed:", e1, "|", e2)

          if not ok:
            # плейсхолдер PDF, если генератор не найден/упал
            from reportlab.lib.pagesizes import A4
            from reportlab.pdfgen import canvas
            c = canvas.Canvas(out, pagesize=A4)
            c.drawString(72, 800, "Sample invoice (placeholder)")
            c.drawString(72, 780, "Input: examples/sample_input.json")
            c.save()
            print("Wrote placeholder:", out)
          else:
            print("Wrote:", out)
          PY

      - name: Create PNG preview from PDF
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils
          # больше DPI — лучше качество превью
          pdftoppm -singlefile -png -rx 200 -ry 200 examples/sample_invoice.pdf examples/sample_invoice
          ls -l examples/

      - name: Commit PNG preview
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add examples/sample_invoice.png
          git commit -m "CI: add/update PNG preview" || echo "No changes"
          git push

      - name: Upload examples as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: examples
          path: examples/
