name: Build sample invoice (manual)

on:
  workflow_dispatch:  # запуск вручную из Actions

permissions:
  contents: write     # нужно, чтобы закоммитить PNG-превью

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Prepare input and run generator
        run: |
          set -e
          mkdir -p invoices examples
          # Подготовим вход (твоя логика — TXT)
          if [ -f invoice_data_example.txt ]; then
            cp -f invoice_data_example.txt invoice_data.txt
          fi
          # Запускаем генерацию; не валим job, если упадёт
          python main.py || true
          # Копируем последний PDF, если он появился
          latest_pdf="$(ls -t invoices/*.pdf 2>/dev/null | head -n 1 || true)"
          if [ -n "$latest_pdf" ]; then
            echo "Found PDF: $latest_pdf"
            cp "$latest_pdf" examples/sample_invoice.pdf
          fi

      - name: Ensure placeholder if no PDF
        run: |
          # Если pdf ещё нет — делаем плейсхолдер (PNG+PDF) через ImageMagick
          if [ ! -f examples/sample_invoice.pdf ]; then
            sudo apt-get update
            sudo apt-get install -y imagemagick
            convert -size 1200x1600 xc:white \
              -pointsize 36 -fill black \
              -draw "text 120,220 'Sample invoice (placeholder)'" \
              -draw "text 120,280 'Input: invoice_data.txt'" \
              examples/sample_invoice.png
            convert examples/sample_invoice.png examples/sample_invoice.pdf
          fi

      - name: Create PNG preview from real PDF (if exists)
        if: hashFiles('examples/sample_invoice.pdf') != ''
        run: |
          # Если PDF есть (реальный или плейсхолдер) — получаем PNG из PDF
          sudo apt-get update
          sudo apt-get install -y poppler-utils
          pdftoppm -singlefile -png -rx 200 -ry 200 \
            examples/sample_invoice.pdf examples/sample_invoice
          ls -l examples/

      - name: Commit PNG preview
        if: hashFiles('examples/sample_invoice.png') != ''
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add examples/sample_invoice.png
          git commit -m "CI: add/update PNG preview" || echo "No changes"
          git push

      - name: Upload examples as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: examples
          path: examples/
