name: Build sample invoice (manual)

on:
  workflow_dispatch:  # ручной запуск из Actions

permissions:
  contents: write     # чтобы закоммитить PNG-превью

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install reportlab

      - name: Build invoice via main.py (or fallback placeholder)
        shell: bash
        run: |
          set -e
          mkdir -p invoices examples

          # 1) подготовим входной файл (TXT)
          if [ -f invoice_data_example.txt ]; then
            cp -f invoice_data_example.txt invoice_data.txt
          fi

          # 2) запуск генерации
          gen_ok=true
          python main.py || gen_ok=false

          # 3) берём свежий PDF из invoices/ или делаем плейсхолдер
          if $gen_ok && ls invoices/*.pdf >/dev/null 2>&1; then
            latest_pdf="$(ls -t invoices/*.pdf | head -n 1)"
            echo "Found PDF: $latest_pdf"
            cp "$latest_pdf" examples/sample_invoice.pdf
          else
            echo "No PDF produced; writing placeholder..."
            python - <<'PY'
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
c = canvas.Canvas("examples/sample_invoice.pdf", pagesize=A4)
c.drawString(72, 800, "Sample invoice (placeholder)")
c.drawString(72, 780, "Input: invoice_data.txt")
c.save()
print("Wrote placeholder: examples/sample_invoice.pdf")
PY
          fi

          ls -l examples/

      - name: Create PNG preview from PDF
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils
          # больше DPI — лучше качество
          pdftoppm -singlefile -png -rx 200 -ry 200 examples/sample_invoice.pdf examples/sample_invoice
          ls -l examples/

      - name: Commit PNG preview
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add examples/sample_invoice.png
          git commit -m "CI: add/update PNG preview" || echo "No changes"
          git push

      - name: Upload examples as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: examples
          path: examples/
